### ISSUE TITLE
error: member access into incomplete type 'mfem::ParGridFunction'

### ISSUE THREAD

**Issue by yurivict** [XBraid/xbraid#55]
```
In file included from drive-diffusion-1D-moving-mesh.cpp:48:
./braid_mfem_block.hpp:37:26: error: member access into incomplete type 'mfem::ParGridFunction'
    for (int i = 0; i < v.Size(); i++)
                         ^
/usr/local/include/mfem/mesh/../fem/tmop.hpp:672:7: note: forward declaration of 'mfem::ParGridFunction'
class ParGridFunction;
      ^
```

I have mfem-4.1 installed, which is the latest version.

**Comment by v-dobrev** [comment]
Can you post the command line (as printed by make) that produces this error? Do you specify any options on the `make` command line?

Also, I assume mfem was installed in `/usr/local`, so it uses the installation layout for the config files, e.g. `config.mk` is in `/usr/local/share/mfem`? In the mfem build directly that file is in a different location -- inside the `config/` subdirectory. This may be causing issues since the `drivers/Makefile` by default assumes `MFEM_DIR` is a build directory and searches for `config.mk` in this location: https://github.com/XBraid/xbraid/blob/a6efbe0f461fac438b500b7b32598d0b6d50ba8e/drivers/Makefile#L43

To override this assumption (when `MFEM_DIR` is an mfem installation directory) one has to also explicitly set `MFEM_CONFIG_MK` on the make command line or edit the `Makefile`. If this assumption was causing problems, I'd expect the make command to error out with the message here: https://github.com/XBraid/xbraid/blob/a6efbe0f461fac438b500b7b32598d0b6d50ba8e/drivers/Makefile#L82

however, since that is not the case, I'm not sure what is going on. Hopefully, my first two questions will help with that.

**Comment by yurivict** [comment]
GNU make is called this way:
```
XDG_DATA_HOME=/usr/ports/math/xbraid/work  XDG_CONFIG_HOME=/usr/ports/math/xbraid/work  HOME=/usr/ports/math/xbraid/work PATH=/usr/ports/math/xbraid/work/.bin:/home/yuri/bin:/sbin:/bin:/usr/sbin:/usr/bin:/usr/local/sbin:/usr/local/bin NO_PIE=yes MK_DEBUG_FILES=no MK_KERNEL_SYMBOLS=no SHELL=/bin/sh NO_LINT=YES PREFIX=/usr/local  LOCALBASE=/usr/local  CC="cc" CFLAGS="-O2 -pipe -fno-omit-frame-pointer  -fstack-protector-strong -fno-strict-aliasing "  CPP="cpp" CPPFLAGS="-fno-omit-frame-pointer"  LDFLAGS=" -fstack-protector-strong " LIBS=""  CXX="c++" CXXFLAGS="-O2 -pipe -fno-omit-frame-pointer -fstack-protector-strong -fno-strict-aliasing -fno-omit-frame-pointer  "  MANPREFIX="/usr/local" BSD_INSTALL_PROGRAM="install  -s -m 555"  BSD_INSTALL_LIB="install  -s -m 0644"  BSD_INSTALL_SCRIPT="install  -m 555"  BSD_INSTALL_DATA="install  -m 0644"  BSD_INSTALL_MAN="install  -m 444" \
gmake \
DESTDIR=/usr/ports/math/xbraid/work/stage
```

mfem-4.1 is installed in ```/jusr/local```.

```config.mk``` is in /usr/local/share/mfem

**Comment by v-dobrev** [comment]
Can you try adding `MFEM_DIR=/usr/local MFEM_CONFIG_MK=/usr/local/share/mfem/config.mk` after `gmake`?

**Comment by jbschroder** [comment]
Hi All,

Due to the inactivity, I'm going to close this.  But we can re-open it if needed.  Just let me know.

- Jacob
