### ISSUE TITLE
Xbraid Convergence

### ISSUE THREAD

**Issue by spyrosArva** [XBraid/xbraid#64]
I am trying to solve a 2D dynamic linear elasticity model using Finite element discetization. The spatial domain is  [0,1]x[0,1] and time domain [0,1]. For time integration I am using a backward Euler scheme . I tried to run a simulation for a small spatial problem(4x4 quadrilateal elements) and 10000 time-steps and I noticed a weird behaviour of Xbraid's residual(a flactuation). At the beginning the residual decreases, for example starts from 3.24e-01 and decreases for the next iterations until  2.45e-04 .Then for few iterations there is a small increasing until 2.09e-03 and the decreases again. Then the residual is decreasing normally until convergence. What may cause this behaviour?Is this normal?
I want to note that I am using a standard coarsening and a FCF relaxation at all levels.V-cycle is used.
I also upload a photo of this behaviour.
![tempsnip](https://user-images.githubusercontent.com/73205160/96929561-974fe400-14ba-11eb-9f58-a04baa8e6cc8.png)

**Comment by beauof** [comment]
Hi @spyrosArva,

I believe that what is happening is that you may have reached discretization accuracy, which is why you seem to have reached a plateau in terms of residuals.

The fact that the residual starts slowly decreasing again from iteration 72 could be caused by the exactness property of MGRIT. This effectively means that the residual is zero for all those time points (starting at time 0) where the exact solution has been propagated, which is a couple more time points for each MGRIT iteration - the count depends on temporal coarsening, cycling strategy, relaxation scheme, etc.

**Comment by spyrosArva** [comment]
@beauof  I see your point here.Can this behaviour cause instabilities or non convergence if larger girds(temporal or spatial) are used?Or this behaviour is normal?

**Comment by jbschroder** [comment]
Hi All,  MGRIT does do this sometimes for hyperbolic problems, where the convergence rate can be (< 1), then (> 1), and then (<1).  Hyperbolic problems are just hard for parallel-in-time methods.  So, this behavior isn't unprecedented. 

You can try slower coarsening factors (say by 2, 3, or 4) and switching over to F-cycles.  Those can be the quickest routes to faster convergence, but they do make iterations more expensive.

Cheers,

Jacob

**Comment by spyrosArva** [comment]
Thanks a lot.I used an F-cycle and these flactuations at the residual do not appear, and thus I am taking a faster convergence

**Comment by jbschroder** [comment]
Hi All,

Due to inactivity, I'm closing this issue.  But, we can reopen it no problem if there's more to discuss.

- Jacob
