### ISSUE TITLE
Wrong results at coarse time points

### ISSUE THREAD

**Issue by lankes-fzj** [XBraid/xbraid#83]
Hello there,

I am currently facing a problem in XBraid that I cannot solve myself. When I compare the results from XBraid with my sequential time-stepper, it appears that the final results on the coarse time-points are incorrect. In the picture below, I have compared the sequential result (left) with the result from XBraid (right). I am using 2 levels and a coarsening factor of 10:

![grafik](https://user-images.githubusercontent.com/41990335/186404750-43f9567d-130a-4a19-bf1b-692b0874fb1c.png)

As you can see most values (those on the fine grid) are very accurate, but every 10th value is wrong (those on the coarse grid at t=..., 0.07, 0.08, 0.09, 0.1). This also happens when I choose a very small (absolute or relative) error tolarance of $10^{-9}$ or less. It seems like the access-function is giving me the coarse propagations (or so) instead of the more accurate results from the finest level. I would guess it has something to do with the C-releaxation or restriction-step and the results on the finest grid are not processed to the coarse grid correctly, but I am not sure, since debugging XBraid was quite hard.

I already tried different versions of XBraid (v3.0.0, v2.3.0 and master) and all are giving me the same results. So I am pretty sure, that it is not a bug in XBraid, but rather a misconfiguration of my project. I bet it would be very easy to solve by someone who knows better how XBraid works. That's why I wanted to quickly ask you before investing more and more time in a trial-and-error approach for something that looks so easy. Maybe I just have to enable or disable a specific option or define another user function. I already tried various options, but none of them were working. Currently, I am only using the minimal set of user-functions as described in "the simplest example".

I hope you can give me a hint. It could save me a lot of time.

Thanks in advance :)

**Comment by rfalgout** [comment]
Hi @lankes-fzj ,

It doesn't make sense that the F-points are correct while the C-points are not, but I'd like to get some additional details.  Is the final residual small, i.e., does the code think it has converged?  How many iterations did you run?  How many relaxation steps are you doing?  What is your initial guess?  Is this all on one processor?

There are a couple of things you should do first when debugging a new driver:
- Run with only 1 level and call `braid_SetRelaxOnlyCG(core, 1)` to tell braid to only do relaxation on that level (instead of solving it sequentially).  After N/10 relaxations (where N is the number of time points), you should have the exact time-stepping solution.
- If the above works, run with 2 levels and start with the exact solution as the initial guess by calling `braid_SetSeqSoln(core, 1)`.  Set the stopping criteria to 0 and force the code to iterate to max iterations.  Here, the residual should stay small.

My guess is that there is something wrong in your Access routine because I can't imagine how the C-points can be wrong while the F-points are correct, but maybe there is something else going on.  Let me know.  Thanks!

-Rob

**Comment by lankes-fzj** [comment]
Hi @rfalgout,

first of all thanks for the quick response.

The final residual is 0 in most cases. and it takes 11 iterations, which is the maximum possible for 100 time steps, right? Usually I use 1 relaxation steps (the default setting), but I also tried different settings (from 0 to 5). All of them came to the same result. I am only using a single processor.

Your suggestions:

- With only 1 level the result equals the sequential solution. On a first try using `SetRelaxOnlyCG(1)`, the result at least equals the sequential result until t=0.19, but afterwards it becomes even worse than my original problem.
  Since I didn't know about this option before, I'll try it with some other parameter constellations and see if I can figure something out.
- When using `SetSeqSoln(1)` and the absolute error tolerance set to 0, the solution equals the sequential one as expected (still with only 1 level), but with 2 levels the results on the C-points are wrong again (exactly the same result as originally described). The residual is 0 in both cases.

I'd like to add, that I'm using the C++-Wrapper. Would it make sense to use the C library instead?

I also suspected the Accesss function, but since it only reads the values and does not change them, this can't be the case, can it? It actually looks to me like XBraid really believes this is the exact solution. Or it has the correct solution somewhere, but just gives me different values.

**Comment by rfalgout** [comment]
Hi @lankes-fzj ,

Just to verify something... With the 1-level setting and `SetRelaxOnlyCG`, are you saying that the code eventually converges to the correct solution everywhere?  And for your comment about t=0.19, was this after 1 iteration (with number of relaxation steps set to 1)?  If so, then this is working as it should.  With these settings, after 1 iteration the first set of F-points, the next C-point, and the next set of F-points should all be exact.  That would take you to t=0.19 if I am reading this right.  After the second iteration, the next C-point and next set of F-points should then also be correct, and so on for each iteration until you get to N/10 iterations where the entire solution should then be the same as with time stepping.

Since your 2-level fixed-point test is still generating incorrect output but telling you that the residual is zero, it still would seem like the Access function is the issue.  That is, the solution being printed out is not what the code is actually computing.  Are you doing anything fancy in your Access function?  In particular, do you have any C/F or level-dependent code there?  Let me know.

The C++ interface shouldn't be an issue.

**Comment by lankes-fzj** [comment]
> With the 1-level setting and SetRelaxOnlyCG, are you saying that the code eventually converges to the correct solution everywhere?

No, I wanted to say, that the solution is correct when using 1 level *without* `SetRelaxOnlyCG`. Sorry for the confusion.

> And for your comment about t=0.19, was this after 1 iteration (with number of relaxation steps set to 1)? If so, then this is working as it should. With these settings, after 1 iteration the first set of F-points, the next C-point, and the next set of F-points should all be exact. That would take you to t=0.19 if I am reading this right

Yes, this happens after one iteration. The result is correct until t=0.019 (not 0.19 as I said before), meaning the first two sets of F-points (t=0.001..0.009 and t=0.011..0.019) and the first C-point (t=0.01) are correct.

> After the second iteration, the next C-point and next set of F-points should then also be correct, and so on for each iteration until you get to N/10 iterations where the entire solution should then be the same as with time stepping.

I just checked and it's as you said: With 2 iterations the result is correct until t=0.029, with 3 iterations until t=0.039 and so on. With 9 iterations almost everything is correct (until t=0.099) and with 10 iterations also the last value (t=0.1) is correct.

But all this only works with the absolute error tolerance set to 0. With an error tolerance of e.g. 1e-9, XBraid terminates after 1 iteration with the residual norm being 0.

> Since your 2-level fixed-point test is still generating incorrect output but telling you that the residual is zero, it still would seem like the Access function is the issue. That is, the solution being printed out is not what the code is actually computing. Are you doing anything fancy in your Access function? In particular, do you have any C/F or level-dependent code there? Let me know.

My access function only has a single line, that stores the results in a map (to sort them in the right order).

**Comment by lankes-fzj** [comment]
I could finally resolve the problem. It appears that there was an error in my `Sum`-function that I didn't noticed for weeks. Parts of the result weren't written to the result vector `y`, beacuse I forgot a single ampersand to make the object a reference 🤦‍♂️ 

I'm sorry, if I wasted your time...
